apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-backend
  labels:
    app: email-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-backend
  template:
    metadata:
      labels:
        app: email-backend
    spec:
      containers:
        - name: email-backend
          image: 730335297276.dkr.ecr.us-east-1.amazonaws.com/email-backend:latest
          ports:
            - containerPort: 80
